name: Frontend CI

on:
  push:
    paths: [frontend/**]
  pull_request:
    paths: [frontend/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Attempt to build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/package.json"

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run build
  lint:
    name: Check style
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/package.json"

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npx eslint
